import { SendEmailCommand }  from "@aws-sdk/client-ses";
import sesClient from "./sesClient";

const sendEmail = (toAddress: string, messageBody: string, messageSubject: string) => {
    const params = {
      Destination: {
        ToAddresses: [toAddress],
      },
      Message: {
        Body: {
          Html: {
            Charset: "UTF-8",
            Data: `<p>${messageBody}</p><br><p>This is an autogenerated message. Please do not reply.</p>`,
          },
        },
        Subject: {
          Charset: "UTF-8",
          Data: messageSubject,
        },
      },
      Source: "arkadiptadas98@outlook.com"
    }
    return sesClient.send(new SendEmailCommand(params))
}

export default sendEmail